Repository la-vie-est-belle-application/Client, pull requests merged in 2024-02, with the labels that each got.

#1 Add: 프로젝트 초기 세팅 완료
  .eslintrc.cjs
  .storybook/main.ts
  .storybook/preview.ts
  craco.config.ts
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Configure.mdx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/assets/accessibility.png
  src/stories/assets/accessibility.svg
  src/stories/assets/addon-library.png
  src/stories/assets/assets.png
  src/stories/assets/avif-test-image.avif
  src/stories/assets/context.png
  src/stories/assets/discord.svg
  src/stories/assets/docs.png
  src/stories/assets/figma-plugin.png
  src/stories/assets/github.svg
  src/stories/assets/share.png
  src/stories/assets/styling.png
  src/stories/assets/testing.png
  src/stories/assets/theming.png
  src/stories/assets/tutorials.svg
  src/stories/assets/youtube.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
  tsconfig.json
  tsconfig.paths.json
Labels: enhancement

#2 Fix: Module import 오류 수정
  .prettierignore
  commitlint.config.cjs
  craco.config.cjs
  package.json
  public/index.html
  src/App.tsx
  src/index.tsx
  src/stories/Button.tsx
  src/stories/Header.tsx
  tsconfig.json
Labels: Fix

#4 Chore : zustand & react-query 셋팅
  package.json
  pnpm-lock.yaml
  src/index.tsx
  src/store/store.ts
Labels: Chore

#5 Add: 기본 폴더 구조 완성
  public/assets/react.svg
  src/common/components/1
  src/common/styles/1
  src/constants/1
  src/hooks/1
  src/layout/1
  src/mocks/1
  src/pages/1
  src/stores/store.ts
  src/tests/1
  src/utils/1
Labels: Add
