Repository la-vie-est-belle-application/Client, pull requests merged in 2024-03, with the labels that each got.

#6 Chore: 기본 프로젝트 설정 완료
  .husky/commit-msg
  .prettierrc
  README.md
  commitlint.config.cjs
  craco.config.cjs
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/common/components/Test.tsx
  src/common/styles/1
  src/index.tsx
  src/main.css
  src/main.tsx
  tsconfig.paths.json
  vite.config.ts
Labels: Chore

#7 Add: color & font 객체 선언 및 이미지 asset 폴더에 추가
  public/assets/coin_2434499.png
  public/assets/free-icon-clipboard-1600196.png
  public/assets/free-icon-hand-1077874 1.png
  public/assets/free-icon-megaphone-1533294.png
  public/assets/free-icon-pie-chart-7665224.png
  public/assets/free-icon-profile-3135715.png
  public/assets/free-icon-schedule-7917776.png
  public/assets/glass_14974623.png
  public/assets/image 2.png
  public/assets/react.svg
  public/vite.svg
  src/constants/1
  src/constants/color.ts
  src/constants/font-size.ts
Labels: Add

#8 Feat: Typography 컴포넌트 생성
  src/App.tsx
  src/common/components/1
  src/common/components/Test.tsx
  src/common/components/Typography/Typography.tsx
  src/constants/color.ts
  src/constants/font-size.ts
  src/constants/typography.ts
Labels: Feat

#9 Feat: typography 컴포넌트 수정
  package.json
  pnpm-lock.yaml
  src/App.css
  src/App.tsx
  src/common/components/ScheduleDetailLink/ScheduleDetailLink.tsx
  src/common/components/Typography/Typography.tsx
  src/constants/color.ts
  src/main.css
  src/pages/1
  src/pages/Home.tsx
Labels: Feat, Add

#12 Feat: typography storybook 등록 완료
  src/App.css
  src/common/components/ScheduleDetailLink/ScheduleDetailLink.tsx
  src/constants/typography.ts
  src/stories/Page.tsx
  src/stories/Typography/Typography.css
  src/stories/Typography/Typography.stories.tsx
  src/stories/Typography/Typography.tsx
  src/stories/header.css
Labels: Feat

#13 Refactor: 버튼 테스트 컴포넌트 리팩토링
  .storybook/main.ts
  package.json
  pnpm-lock.yaml
  src/common/components/Button/Button.tsx
  src/common/components/Button/buttonStyle.ts
  src/pages/Home.tsx
  src/stories/Button/Button.stories.tsx
  src/stories/Button/Button.tsx
Labels: Refactor
