Repository la-vie-est-belle-application/Client, pull requests merged in 2024-05, with the labels that each got.

#17 Feat: story 구현 및 수정
  public/assets/chart.svg
  public/assets/clipboard.svg
  public/assets/glass.svg
  public/assets/hand.svg
  public/assets/main.svg
  public/assets/megaphone.svg
  public/assets/profile.svg
  public/assets/schedule-blue.svg
  public/assets/schedule-red.svg
  public/assets/tiger.svg
  src/stories/Button/Button.stories.tsx
  src/stories/Card/Card.stories.tsx
  src/stories/Card/Card.tsx
  src/stories/Chakra/Button/Button.stories.tsx
  src/stories/Chakra/Icon/Icon.tsx
  src/stories/Image/Image.tsx
  src/stories/Image/image.stories.tsx
  src/stories/assets/chat.svg
  src/stories/assets/setting.svg
  src/stories/assets/sign-out.svg
Labels: Feat, Chore

#18 Feat: 스케쥴 디테일 링크 컴포넌트 완성
  src/common/components/ScheduleDetailLink/ScheduleDetailLink.tsx
  src/pages/Home.tsx
Labels: Feat

#19 Feat: 로그인 페이지 퍼블리싱 완료
  src/App.css
  src/App.tsx
  src/common/components/Button/buttonStyle.ts
  src/pages/SignIn.tsx
Labels: Feat

#20 Feat: 일정관리 페이지 구현
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/common/components/Button/buttonStyle.ts
  src/common/components/Calender/Calender.tsx
  src/common/components/ViewSchedule/ViewSchedule.tsx
  src/layout/1
  src/layout/Header.tsx
  src/main.css
  src/pages/Home.tsx
  src/pages/ScheduleManage.tsx
Labels: Feat

#21 Feat: 일정 관리 페이지 백그라운드 및 토글버튼 구현
  src/App.css
  src/App.tsx
  src/common/components/Button/buttonStyle.ts
  src/common/components/Calender/Calender.tsx
  src/common/components/ViewSchedule/BackGroundBlur.tsx
  src/common/components/ViewSchedule/ViewSchedule.tsx
  src/stores/store.ts
Labels: Feat, Chore

#22 Feat: main 페이지 퍼블리싱 완료
  package.json
  pnpm-lock.yaml
  public/assets/AiFillMessage.svg
  public/assets/ckPhone.svg
  public/assets/schedule-green.svg
  src/App.css
  src/App.tsx
  src/common/components/Button/Button.tsx
  src/common/components/Button/buttonStyle.ts
  src/common/components/Container/Container.tsx
  src/common/components/Typography/Typography.tsx
  src/constants/color.ts
  src/datas/Admins.json
  src/datas/Menus.json
  src/layout/Header.tsx
  src/pages/Home.tsx
  src/pages/SignIn.tsx
  src/pages/home/Home.tsx
  src/pages/home/components/AdminsProfileCard.tsx
  src/pages/home/components/Menus.tsx
  src/pages/home/components/ScheduleRegistrationCard.tsx
  src/pages/home/components/SwiperAdminsProfileCard.tsx
  src/pages/home/components/UserProfile.tsx
  src/pages/signIn/SignIn.tsx
  tsconfig.paths.json
  vite.config.ts
Labels: Feat

#23 Feat: modal 구현
  src/App.tsx
  src/common/components/Button/buttonStyle.ts
  src/common/components/Modal/BackGroundBlur.tsx
  src/common/components/Modal/Modal.tsx
  src/common/components/ViewSchedule/ViewSchedule.tsx
  src/stores/store.ts
Labels: Feat, Chore

#24 Feat: notice 페이지 퍼블리싱 완료 및 Modal 컴포넌트 props 수정, Modal test constant 추가
  src/App.tsx
  src/common/components/Modal/Modal.tsx
  src/constants/modalText.ts
  src/pages/notice/Notice.tsx
Labels: Feat

#25 Feat: 등록폼 구현
  src/App.tsx
  src/common/components/Button/buttonStyle.ts
  src/common/components/Calender/Calender.tsx
  src/common/components/Modal/BackGroundBlur.tsx
  src/common/components/Modal/Modal.tsx
  src/common/components/Modal/RegisterForm/RegisterForm.tsx
  src/common/components/Modal/RegisterForm/components/MemberList.tsx
  src/common/components/Modal/RegisterForm/components/MemberTag.tsx
  src/common/components/Modal/RegisterForm/components/ScheduleTable.tsx
  src/common/components/ViewSchedule/ViewSchedule.tsx
  src/datas/Member.json
  src/datas/Position.json
  src/layout/Header.tsx
  src/pages/ScheduleRegister.tsx
  src/stores/store.ts
Labels: Feat

#26 Refactor: 스케줄 등록폼 모달 상태관리 및 버튼 컴포넌트 코드 리팩토링
  src/common/components/Button/ButtonGroup.tsx
  src/common/components/Modal/Modal.tsx
  src/common/components/Modal/RegisterForm/RegisterForm.tsx
  src/common/components/ViewSchedule/ViewSchedule.tsx
Labels: Feat, Refactor

#27 Feat: 메뉴모달 구현
  src/common/components/Button/ButtonGroup.tsx
  src/common/components/Button/buttonStyle.ts
  src/common/components/Modal/BackGroundBlur.tsx
  src/common/components/Modal/Menu/Menu.tsx
  src/common/components/Modal/Menu/components/MenuBody.tsx
  src/common/components/Modal/Menu/components/MenuFooter.tsx
  src/common/components/Modal/Menu/components/MenuHeader.tsx
  src/common/components/Modal/RegisterForm/RegisterForm.tsx
  src/layout/Header.tsx
  src/stores/store.ts
Labels: Feat, Design, Refactor

#28 Chore: 스케줄 등록 페이지 폴더구조 정리 및 컴포넌트 높이, 간격 수정
  src/App.tsx
  src/common/components/Modal/Menu/components/MenuBody.tsx
  src/common/components/Modal/Menu/components/MenuFooter.tsx
  src/common/components/Modal/RegisterForm/RegisterForm.tsx
  src/common/components/Modal/RegisterForm/components/MemberList.tsx
  src/common/components/Modal/RegisterForm/components/MemberTag.tsx
  src/common/components/Modal/RegisterForm/components/ScheduleTable.tsx
  src/layout/Header.tsx
  src/pages/ScheduleManage.tsx
  src/pages/ScheduleRegister.tsx
  src/pages/scheduleManagement/ScheduleManage.tsx
  src/pages/scheduleManagement/ScheduleRegister.tsx
  src/pages/scheduleManagement/components/Calender.tsx
  src/pages/scheduleManagement/components/ManagementContainer.tsx
  src/pages/scheduleManagement/components/ViewSchedule.tsx
Labels: Chore
