Repository la-vie-est-belle-application/Client, pull requests merged in 2025-04, with the labels that each got.

#67 Feat: supabase 기본 설정
  .github/ISSUE_TEMPLATE/기능-구현.md
  .github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md
  .husky/prepare-commit-msg
  .prettierrc
  .vscode/setting.json
  app/favicon.ico
  app/globals.css
  app/layout.tsx
  app/page.tsx
  app/sign-up/page.tsx
  eslint.config.mjs
  package-lock.json
  package.json
  src/__test__/page.test.tsx
  src/app/page.tsx
  src/entities/supabase/index.ts
  tsconfig.json
Labels: Feat

#72 Feature: 스케줄 등록 퍼블리싱
  app/(dashboard)/layout.tsx
  app/globals.css
  components/ui/button.tsx
  components/ui/calendar.tsx
  components/ui/index.ts
  package-lock.json
  package.json
  src/feature/schedule-manage/index.ts
  src/feature/schedule-manage/ui/create-schedule.tsx
  src/feature/schedule-manage/ui/filter-schedule.tsx
  src/feature/schedule-manage/ui/show-schedule-card.tsx
  src/views/schedule-manage/index.ts
  src/views/schedule-manage/schedule-manage.tsx
  src/views/schedule-manage/ui/Page/schedule-manage.tsx
  src/views/schedule-manage/ui/calender.css
  src/views/schedule-manage/ui/schedule-calender.tsx
  src/widgets/header/header.tsx
  src/widgets/side-bar/ui/side-bar.tsx
Labels: Design, Add

#74 Feature: 스케줄 관리 퍼블리싱
  app/(dashboard)/layout.tsx
  app/(dashboard)/schedule-dashboard/[manage]/page.tsx
  app/(dashboard)/schedule-dashboard/page.tsx
  app/(dashboard)/schedule-manage/page.tsx
  components/ui/card.tsx
  components/ui/checkbox.tsx
  components/ui/index.ts
  components/ui/select.tsx
  components/ui/table.tsx
  package-lock.json
  package.json
  src/feature/schedule-manage/index.ts
  src/feature/schedule-manage/ui/schedule-modal.tsx
  src/feature/schedule-manage/ui/select.tsx
  src/views/schedule-manage/index.ts
  src/views/schedule-manage/ui/Page/schedule-manage.tsx
  src/views/schedule-manage/ui/Page/schedule-register.tsx
  src/views/schedule-manage/ui/position-table.tsx
  src/widgets/container/container.tsx
  src/widgets/container/index.ts
Labels: Design, Add

#76 Feature: 스케줄 대시보드 라우팅 구현
  app/(dashboard)/layout.tsx
  app/(dashboard)/member-dashboard/page.tsx
  app/(dashboard)/schedule-dashboard/manage/page.tsx
  app/(dashboard)/schedule-dashboard/register/page.tsx
  components/ui/dialog.tsx
  components/ui/index.ts
  package-lock.json
  package.json
  src/feature/schedule-manage/ui/schedule-modal.tsx
  src/views/schedule-manage/ui/Page/schedule-manage.tsx
  src/views/schedule-manage/ui/position-table.tsx
  src/widgets/header/header.tsx
  src/widgets/side-bar/ui/side-bar.tsx
Labels: Design, Add

#78 Feature: 테스트 코드 작성
  src/entities/schedule-card/api/get-schedule-preview.test.ts
  src/entities/schedule-card/api/get-schedule-preview.ts
  src/entities/schedule-card/api/types.ts
  src/entities/schedule-card/index.ts
  src/entities/schedule-card/ui/show-schedule-card.tsx
  src/feature/schedule-manage/index.ts
  src/widgets/side-bar/ui/schedule-panel.tsx
Labels: Test
